// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAteKWbPU6Ujn2uOW-1P4Fv0Lzh7gLPOdM',
    appId: '1:226149164109:web:1de718fb7121c39bd62804',
    messagingSenderId: '226149164109',
    projectId: 'firemovies-d3c6b',
    authDomain: 'firemovies-d3c6b.firebaseapp.com',
    storageBucket: 'firemovies-d3c6b.appspot.com',
    measurementId: 'G-GPTNSZS0HD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVI1a6B4W2b3w5HuYpy5bcBE26rMGa84w',
    appId: '1:226149164109:android:3e9e223d1c34fe15d62804',
    messagingSenderId: '226149164109',
    projectId: 'firemovies-d3c6b',
    storageBucket: 'firemovies-d3c6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp-RS9hSQP3tOrE_8w-zg8vrRpJMk39G8',
    appId: '1:226149164109:ios:60b9c698a64761bed62804',
    messagingSenderId: '226149164109',
    projectId: 'firemovies-d3c6b',
    storageBucket: 'firemovies-d3c6b.appspot.com',
    iosClientId: '226149164109-e4r533d9o5cjnhadamnaliofh4deo29h.apps.googleusercontent.com',
    iosBundleId: 'com.example.filmWiseMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp-RS9hSQP3tOrE_8w-zg8vrRpJMk39G8',
    appId: '1:226149164109:ios:60b9c698a64761bed62804',
    messagingSenderId: '226149164109',
    projectId: 'firemovies-d3c6b',
    storageBucket: 'firemovies-d3c6b.appspot.com',
    iosClientId: '226149164109-e4r533d9o5cjnhadamnaliofh4deo29h.apps.googleusercontent.com',
    iosBundleId: 'com.example.filmWiseMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAteKWbPU6Ujn2uOW-1P4Fv0Lzh7gLPOdM',
    appId: '1:226149164109:web:d5c53fb231515d1cd62804',
    messagingSenderId: '226149164109',
    projectId: 'firemovies-d3c6b',
    authDomain: 'firemovies-d3c6b.firebaseapp.com',
    storageBucket: 'firemovies-d3c6b.appspot.com',
    measurementId: 'G-XGND9B202M',
  );
}
